# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install xvfb
      run: sudo apt-get install xvfb
    - name: installiere npm
      run: npm i
           xvfb-run --auto-servernum npm test
    - name: Build with Maven
      run: mvn -Pnu -Pgui clean -X verify
